apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio
  name: minio
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
  selector:
    app: minio
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: minio-claim0
  name: minio-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: minio-claim1
  name: minio-claim1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: minio
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - args:
            - server
            - /data
          env:
            - name: MINIO_ACCESS_KEY
              value: minioadmin
            - name: MINIO_SECRET_KEY
              value: minioadmin
          image: minio/minio:RELEASE.2020-11-10T21-02-24Z
          imagePullPolicy: ""
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:9000/minio/health/live
            failureThreshold: 3
            periodSeconds: 30
            timeoutSeconds: 20
          name: minio
          ports:
            - containerPort: 9000
          volumeMounts:
            - mountPath: /data
              name: minio-claim0
            - mountPath: /root/.minio
              name: minio-claim1
      volumes:
        - name: minio-claim0
          persistentVolumeClaim:
            claimName: minio-claim0
        - name: minio-claim1
          persistentVolumeClaim:
            claimName: minio-claim1
