apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
  name: mongo
spec:
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mongo
  name: mongo
spec:
  serviceName: mongo
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - args:
            - mongod
            - --oplogSize
            - "128"
            - --profile=1
            - --slowms=500
            - --replSet
            - rs0
          image: mongo:4.2
          name: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongo-data
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: slow
        resources:
          requests:
            storage: 10Mi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mongo-init-replica
  name: mongo-init-replica
spec:
  serviceName: mongo
  replicas: 1
  selector:
    matchLabels:
      app: mongo-init-replica
  template:
    metadata:
      labels:
        app: mongo-init-replica
    spec:
      containers:
        - args:
            - bash
            - -c
            - |-
              for i in `seq 1 30`; do
                  mongo mongo/steedos --eval "
                    rs.initiate({
                      _id: 'rs0',
                      members: [ { _id: 0, host: 'localhost:27017' } ]})" &&
                  s=$? && break || s=$?;
                  echo "Tried $i times. Waiting 5 secs...";
                  sleep 5;
                done; (exit $s)
          image: mongo:4.2
          name: mongo-init-replica
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slow
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
