apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: steedos
  name: steedos
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: steedos
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: steedos
    spec:
      containers:
      - env:
        - name: MONGO_OPLOG_URL
          value: mongodb://mongo:27017/local
        - name: MONGO_URL
          value: mongodb://mongo:27017/steedos
        - name: PORT
          value: "5080"
        - name: ROOT_URL
          value: http://localhost:5080
        - name: STEEDOS_CFS_STORE
          value: local
        - name: STEEDOS_STORAGE_DIR
          value: /app/storage
        image: steedos/steedos-project-oa:1.22.1
        imagePullPolicy: ""
        name: steedos
        ports:
        - containerPort: 5080
        resources: {}
        volumeMounts:
        - mountPath: /app/storage
          name: steedos-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: steedos-claim0
        persistentVolumeClaim:
          claimName: steedos-claim0
status: {}
