apiVersion: v1
kind: Service
metadata:
  labels:
    app: steedos
  name: steedos
spec:
  type: NodePort
  ports:
  - port: 5080
    targetPort: 5080
  selector:
    app: steedos
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: steedos
  name: steedos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: steedos
  template:
    metadata:
      labels:
        app: steedos
    spec:
      containers:
      - env:
        - name: MONGO_OPLOG_URL
          value: mongodb://mongo:27017/local
        - name: MONGO_URL
          value: mongodb://mongo:27017/steedos
        - name: PORT
          value: "5080"
        - name: ROOT_URL
          value: http://localhost:5080
        - name: STEEDOS_CFS_STORE
          value: local
        - name: STEEDOS_STORAGE_DIR
          value: /app/storage
        image: steedos/steedos-project-oa:1.22.1
        name: steedos
        ports:
        - containerPort: 5080
        volumeMounts:
        - mountPath: /app/storage
          name: steedos-claim0
      volumes:
      - name: steedos-claim0
        persistentVolumeClaim:
          claimName: steedos-claim0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: steedos-claim0
  name: steedos-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi